### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by jessereitz** [jessereitz/WriteFree#4]
## What
We need tests. On everything. There aren't anything. That's bad.

## Fix
Write some dang test. 

## To-Do
- [ ] Explore testing frameworks
- [ ] Implement chosen framework
- [ ] Write tests (maybe even hit 100% coverage???)
- [ ] Run builds through CI framework
